# Paths
bam_root: "/storage/scratch01/groups/md/rnaseq_liver_OBECAN/fat/results/mapped/star"
bam_glob: "/storage/scratch01/groups/md/rnaseq_liver_OBECAN/fat/results/mapped/star/*/Aligned.sortedByCoord.out.bam"

genome_fa: "/storage/scratch01/users/sbarber/Workdir/GRCh38.primary_assembly.genome.fa"
gencode_gtf: "/storage/scratch01/users/sbarber/Workdir/gencode.v38.primary_assembly.annotation.gtf"

# Your helper scripts
filter_smorf_pep_py: "/storage/scratch01/users/sbarber/Workdir/filter_smorf_pep.py"
tx_to_genome_py: "/storage/scratch01/users/sbarber/Workdir/smorfs_transcript_to_genome_gtf.py"
merge_script: "/storage/scratch01/users/sbarber/Workdir/merge_shortstop_output.py"
aggregate_script: "/storage/scratch01/users/sbarber/Workdir/aggregate_smorfs_by_locus.py"

# directories and files
merged_dir: "merged_per_sample"
cohort_prefix: "results_shortstop/cohort.locus_summary"
pred_csv: "sams.csv" # this is ALL SAMs, but we can also use sam_secreted.csv or other 

# aggregation
min_patients: 2

# Output directory
outdir: "results_shortstop"

# Threads
threads_stringtie: 2
threads_shortstop: 2
threads_transdecoder: 2  # TransDecoder itself doesn't parallelize much, but kept for resource planning

# smORF filter
min_aa: 10
max_aa: 150